# Generated by Django 2.1 on 2020-02-28 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='openID',
        ),
        migrations.RemoveField(
            model_name='student',
            name='unionID',
        ),
    ]
