# Generated by Django 2.1 on 2020-02-28 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200228_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='openID',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='unionID',
            field=models.CharField(default='', max_length=50),
        ),
    ]
