# Generated by Django 2.1 on 2020-03-23 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200323_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='openID',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='unionID',
            field=models.CharField(default='', max_length=50),
        ),
    ]
