# Generated by Django 2.1 on 2020-07-24 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='openID',
        ),
        migrations.RemoveField(
            model_name='student',
            name='unionID',
        ),
    ]
