# Generated by Django 2.1 on 2020-07-24 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200724_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='openID',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='unionID',
            field=models.CharField(default='', max_length=50),
        ),
    ]
