# Generated by Django 2.1 on 2020-08-22 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FindObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectName', models.CharField(default='', max_length=50)),
                ('objectImage', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/')),
                ('ownerName', models.CharField(default='', max_length=50)),
                ('ownerID', models.PositiveIntegerField(default='')),
                ('ownerContactWay', models.CharField(default='', max_length=3)),
                ('ownerContactNum', models.CharField(default='', max_length=20)),
                ('remarks', models.CharField(blank=True, max_length=200, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('publisher', models.PositiveIntegerField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='FindOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectName', models.CharField(default='', max_length=50)),
                ('objectImage', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/')),
                ('haveOwnerInfo', models.BooleanField(default=False)),
                ('ownerName', models.CharField(blank=True, max_length=50, null=True)),
                ('ownerID', models.PositiveIntegerField(blank=True, null=True)),
                ('place', models.CharField(default='', max_length=10)),
                ('pickerName', models.CharField(blank=True, max_length=50, null=True)),
                ('pickerContactWay', models.CharField(blank=True, max_length=3, null=True)),
                ('pickerContactNum', models.CharField(blank=True, max_length=20, null=True)),
                ('remarks', models.CharField(blank=True, max_length=200, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('publisher', models.PositiveIntegerField(default='')),
            ],
        ),
    ]
